app:
  name: app

deployment:
  enabled:
    blue: true
    green: true

replicaCount:
  blue: 2
  green: 2

traffic:
  activeColor: blue   # blue | green

image:
  blue:
    repository: nginx
    tag: "1.25"
    pullPolicy: IfNotPresent
  green:
    repository: nginx
    tag: "1.26"
    pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: hello.example.local
  path: /

probes:
  readiness:
    enabled: true
    path: /
    port: 80
  liveness:
    enabled: false
    path: /
    port: 80
